{
 "title": "NGINX METRICS",
 "description": "Performance metrics for Nginx",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "NGINX SERVICE STATUS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://blog.rosnertech.com.br/wp-content/uploads/2025/02/logo_semfundo.png\">"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Service status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": { "filter": "Service status" },
     "itemTag": { "filter": "component: health" },
     "macro": { "filter": "" },
     "measurement": "services_stats",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "nginx.service" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Memory usage (vsize)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": { "filter": "Memory usage (vsize)" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "nginx_access_log",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "request" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^*/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": { "filter": "Requests per second" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "nginx_access_log",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "request" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^*/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": { "filter": "Requests total" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "nginx_access_log",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "request" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^*/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": { "filter": "CPU utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "nginx_access_log",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "request" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^*/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Memory usage, %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": { "filter": "Memory usage, %" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "nginx_access_log",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "request" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^*/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Service response time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": { "filter": "Service response time" },
     "itemTag": { "filter": "component: application" },
     "macro": { "filter": "" },
     "measurement": "services_stats",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "status_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "nginx.service" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Memory usage (rss)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": { "filter": "Memory usage (rss)" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "nginx_access_log",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "request" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^*/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Connections reading",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": { "filter": "Connections reading" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "nginx_access_log",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "request" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^*/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Connections writing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": { "filter": "Connections writing" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "nginx_access_log",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "request" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^*/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "REQUEST TIME",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Request time 2**",
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": {
      "filter": "Connections accepted per second"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "nginx_access_log",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "request_time" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^2/" }
     ],
     "trigger": { "filter": "" }
    },
    {
     "alias": "Request time 3**",
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": { "filter": "Connections dropped per second" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "nginx_access_log",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "SELECT first(\"request_time\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/ AND \"resp_code\" =~ /^3/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "schema": 12,
     "select": [
      [
       { "params": [ "request_time" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^3/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "NGINX STATUS METRICS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": { "filter": "Requests total" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "nginx",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "accepts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "accepts" ], "type": "alias" }
      ],
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "handled" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "handled" ], "type": "alias" }
      ],
      [
       { "params": [ "reading" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "reading" ], "type": "alias" }
      ],
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "requests" ], "type": "alias" }
      ],
      [
       { "params": [ "waiting" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "waiting" ], "type": "alias" }
      ],
      [
       { "params": [ "writing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "writing" ], "type": "alias" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Servidor_Web" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "Nginx" },
     "item": { "filter": "Requests per second" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "nginx",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "accepts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "accepts" ], "type": "alias" }
      ],
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "handled" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "handled" ], "type": "alias" }
      ],
      [
       { "params": [ "reading" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "reading" ], "type": "alias" }
      ],
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "requests" ], "type": "alias" }
      ],
      [
       { "params": [ "waiting" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "waiting" ], "type": "alias" }
      ],
      [
       { "params": [ "writing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "writing" ], "type": "alias" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}