{
 "title": "Docker",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Docker Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://blog.rosnertech.com.br/wp-content/uploads/2025/02/logo_semfundo.png\">"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Containers total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": { "filter": "Containers total" },
     "itemTag": { "filter": "component: containers" },
     "macro": { "filter": "" },
     "measurement": "services_stats",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "slaInterval": "none",
     "slaProperty": "sla",
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "nginx.service" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Containers running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": { "filter": "Containers running" },
     "itemTag": { "filter": "component: containers" },
     "macro": { "filter": "" },
     "measurement": "services_stats",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "slaInterval": "none",
     "slaProperty": "sla",
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "nginx.service" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Containers stopped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": { "filter": "Containers stopped" },
     "itemTag": { "filter": "component: containers" },
     "macro": { "filter": "" },
     "measurement": "services_stats",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "slaInterval": "none",
     "slaProperty": "sla",
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "nginx.service" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Images total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": { "filter": "Images total" },
     "itemTag": { "filter": "component: images" },
     "macro": { "filter": "" },
     "measurement": "services_stats",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "slaInterval": "none",
     "slaProperty": "sla",
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "nginx.service" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Images size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": { "filter": "Images size" },
     "itemTag": { "filter": "component: images" },
     "macro": { "filter": "" },
     "measurement": "services_stats",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "slaInterval": "none",
     "slaProperty": "sla",
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "nginx.service" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CPU percent usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_certbot: CPU percent usage"
     },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_grafana: CPU percent usage"
     },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_portainer: CPU percent usage"
     },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_zabbix_agent: CPU percent usage"
     },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_zabbix_frontend: CPU percent usage"
     },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_zabbix_mariadb: CPU percent usage"
     },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_zabbix_server: CPU percent usage"
     },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_zabbix_snmptraps: CPU percent usage"
     },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": { "filter": "Container /rosnertech_" },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_certbot: Memory usage"
     },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_grafana: Memory usage"
     },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_portainer: Memory usage"
     },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_portainer: Memory usage"
     },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_zabbix_agent: Memory usage"
     },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_zabbix_frontend: Memory usage"
     },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_zabbix_mariadb: Memory usage"
     },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_zabbix_server: Memory usage"
     },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "VPS - CHEWBACCA" },
     "item": {
      "filter": "Container /rosnertech_zabbix_snmptraps: Memory usage"
     },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}